version: '3.8'

services:
  api_gateway:
    build:
      context: .
      dockerfile: /api_gateway/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - flask_db

  tasks:
    build:
      context: .
      dockerfile: /tasks/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - flask_db
  
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}