# Imagen base
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . .

# Instalar dependencias del sistema necesarias para crear el entorno virtual
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Crear un entorno virtual y configurar el entorno
RUN python -m venv /venv \
    && /venv/bin/pip install --upgrade pip \
    && /venv/bin/pip install -r requirements.txt

# Configurar el PATH para usar el entorno virtual por defecto
ENV PATH="/venv/bin:$PATH"

# Exponer el puerto 5000 para el servidor Flask
EXPOSE 5000

# Comando para iniciar el servidor Flask
CMD ["sh", "-c", "cd process_videos && flask run --host=0.0.0.0 --port=5000"]